# Generated by Django 5.0.7 on 2024-08-08 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pub', models.DateField(auto_now_add=True, verbose_name='publication date')),
                ('pub_title', models.CharField(max_length=100, verbose_name='Título da publicação')),
                ('pub_text', models.TextField(max_length=255, verbose_name='Texto da publicação')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
            options={
                'db_table': 'publications',
            },
        ),
    ]
